language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=3.6 }
    - { os: linux, env: PYTHON_VERSION=3.7 }
    - { os: osx, env: PYTHON_VERSION=3.6 }
    - { os: osx, env: PYTHON_VERSION=3.7 }

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ulimit -n 1024; fi
  - source devtools/travis-ci/install.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels omnia
  - conda config --add channels janschulz
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda create -n test-environment python=$PYTHON_VERSION
  - source activate test-environment
  - conda install numpy mbuild pytest nbval py3Dmol

script:
  - python -m pytest -v --nbval --nbval-lax
